title: Hi, I'm Matt!
email: mattkharrison07@gmail.com
description: >
baseurl: "" 
url: "http://localhost:4000" 

github_username: mattie14
linkedin_username: matt-harrison-b1b2b13a

# Build settings
markdown: kramdown
theme: jekyll-swiss
theme_color: white
sass:
  sass_dir: _sass
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
