title: Hi, I'm Matt!
email: mattkharrison07@gmail.com
description: >
baseurl: /website
url: "https://mattie14.github.io" 

github_username: mattie14
linkedin_username: matt-harrison-b1b2b13a

# Build settings
markdown: kramdown
theme: jekyll-swiss
theme_color: black
sass:
  sass_dir: _sass
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
